DEPLOY_TO: 'gcloud-dev'
DEPLOY_TO_PREFIX: 'gcloud'
DEPLOYMENT_TYPE: 'dev'

DOCKER_IMAGE_PREFIX: 'gcr.io/{{ GCLOUD_PROJECT }}'

# gcloud settings
#CLUSTER_NAME: 'hail-db-cluster-dev'
CLUSTER_NAME: 'seqr-cluster-dev'
CLUSTER_MACHINE_TYPE: 'n1-highmem-4'   # n1-standard-2, n1-standard-4 .. n1-standard-64,  n1-highmem-2, n1-highcpu-2 ..
CLUSTER_NUM_NODES: 4

ES_DATA_NUM_PODS: 4
ES_CLIENT_NUM_PODS: 2
ES_MASTER_NUM_PODS: 3

ELASTICSEARCH_DISK_SIZE: 380
ELASTICSEARCH_JVM_MEMORY: 8g