DEPLOY_TO: 'gcloud-dev'
DEPLOY_TO_PREFIX: 'gcloud'
DEPLOYMENT_TYPE: 'dev'

DOCKER_IMAGE_PREFIX: 'gcr.io/{{ GCLOUD_PROJECT }}'

# gcloud settings
#CLUSTER_NAME: 'hail-db-cluster-dev'
CLUSTER_NAME: 'ssd-seqr-cluster2-dev'
CLUSTER_MACHINE_TYPE: 'n1-highmem-2'   # n1-standard-2, n1-standard-4 .. n1-standard-64,  n1-highmem-2, n1-highcpu-2 ..
CLUSTER_NUM_NODES: 8

ES_DATA_NUM_PODS: 8
ES_CLIENT_NUM_PODS: 2
ES_MASTER_NUM_PODS: 3
