VERSION: 0.1

#GCLOUD_PROJECT: 'broad-mpg-gnomad'
GCLOUD_PROJECT: 'seqr-project'
GCLOUD_ZONE: 'us-central1-b'

DEPLOYMENT_TEMP_DIR: '/tmp'

COCKPIT_SERVICE_PORT: 9090
ELASTICSEARCH_SERVICE_PORT: 30001
KIBANA_SERVICE_PORT: 30002

ELASTICSEARCH_DISK_SIZE: '200Gb'
